// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCuaIpaVSksfpaCFyoNQhhEZiasgPJ51uY',
    appId: '1:531331251681:web:b2982f39979d1f2bff66a0',
    messagingSenderId: '531331251681',
    projectId: 'safe-pick-app',
    authDomain: 'safe-pick-app.firebaseapp.com',
    storageBucket: 'safe-pick-app.firebasestorage.app',
    measurementId: 'G-8HNN58RGWR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDObqqic5x8OXBEK4ITHNtQazX0IhV7JwI',
    appId: '1:531331251681:android:a2b0f4ea7b4e6b0cff66a0',
    messagingSenderId: '531331251681',
    projectId: 'safe-pick-app',
    storageBucket: 'safe-pick-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1Wfc5OsBLnzp7FoIbe_f7XTN3mjyJKV0',
    appId: '1:531331251681:ios:1dc6ee8e3420795dff66a0',
    messagingSenderId: '531331251681',
    projectId: 'safe-pick-app',
    storageBucket: 'safe-pick-app.firebasestorage.app',
    iosBundleId: 'com.safepick.safePick',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1Wfc5OsBLnzp7FoIbe_f7XTN3mjyJKV0',
    appId: '1:531331251681:ios:1dc6ee8e3420795dff66a0',
    messagingSenderId: '531331251681',
    projectId: 'safe-pick-app',
    storageBucket: 'safe-pick-app.firebasestorage.app',
    iosBundleId: 'com.safepick.safePick',
  );
}
